spring.application.name=CatalogoParametrosUcoLab
surrealdb.url=http://localhost:8000
surrealdb.namespace=catalogo_parametros
surrealdb.database=catalogo_parametros
surrealdb.username=root
surrealdb.password=root

# Actuator & Metrics
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
