spring.application.name=CatalogoParametrosUcoLab
surrealdb.url=http://localhost:8000
surrealdb.namespace=catalogo_parametros
surrealdb.database=catalogo_parametros
surrealdb.username=root
surrealdb.password=root
