spring.application.name=${application-name}

spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://parametersucolab.vault.azure.net/

azure.keyvault.client.endpoint=https://parametersucolab.vault.azure.net/

surrealdb.url=${surrealdb-url}
surrealdb.namespace=${surrealdb-namespace}
surrealdb.database=${surrealdb-database}
surrealdb.username=${surrealdb-username}
surrealdb.password=${surrealdb-password}

# Actuator & Metrics

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
