package co.edu.uco.CatalogoParametrosUcoLab.application.features.estadoambiente.actualizarestadoambiente;
import co.edu.uco.CatalogoParametrosUcoLab.application.features.estadoambiente.actualizarestadoambiente.usecase.domain.ActualizarEstadoAmbienteDomain;
import co.edu.uco.CatalogoParametrosUcoLab.application.usecase.validator.RuleValidator;
public interface ActualizarEstadoAmbienteRuleValidator extends RuleValidator<ActualizarEstadoAmbienteDomain> { }
