package co.edu.uco.CatalogoParametrosUcoLab.application.features.estadometadatoambiente.actualizarestadometadatoambiente;
import co.edu.uco.CatalogoParametrosUcoLab.application.features.estadometadatoambiente.actualizarestadometadatoambiente.usecase.domain.ActualizarEstadoMetadatoAmbienteDomain;
import co.edu.uco.CatalogoParametrosUcoLab.application.usecase.validator.RuleValidator;
public interface ActualizarEstadoMetadatoAmbienteRuleValidator extends RuleValidator<ActualizarEstadoMetadatoAmbienteDomain> { }
