package co.edu.uco.CatalogoParametrosUcoLab.application.features.estadometadatoambiente.crearestadometadatoambiente;
import co.edu.uco.CatalogoParametrosUcoLab.application.features.estadometadatoambiente.crearestadometadatoambiente.usecase.domain.CrearEstadoMetadatoAmbienteDomain;
import co.edu.uco.CatalogoParametrosUcoLab.application.usecase.validator.RuleValidator;
public interface CrearEstadoMetadatoAmbienteRuleValidator extends RuleValidator<CrearEstadoMetadatoAmbienteDomain> { }
