package co.edu.uco.CatalogoParametrosUcoLab.application.features.funcionalidad.crearfuncionalidad.primaryports.interactor;

import co.edu.uco.CatalogoParametrosUcoLab.application.features.funcionalidad.crearfuncionalidad.primaryports.dto.CrearFuncionalidadDtoRequest;
import co.edu.uco.CatalogoParametrosUcoLab.application.primaryports.InteractorWithOutReturn;

public interface CrearFuncionalidadInteractor extends InteractorWithOutReturn<CrearFuncionalidadDtoRequest> {
}